### ISSUE TITLE
[BUG] Import doesn't work in phpmyadmin

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/ansible-AlternC#16]
In phpmyadmin, managing a database, pressing "Import" gives: 
![imagen](https://user-images.githubusercontent.com/24596190/121759616-e2c40a80-cafc-11eb-82c1-63b5a1b89758.png)

**Comment by ulvida** [comment]
@andrespias reports this error log in `/var/log/apache2/error.log`:
```
[Fri Jun 11 17:14:06.112791 2021] [php7:error] [pid 32484] [client 2001:1328:6a:5::1004:40688] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unknown "spaceless" filter. in /usr/share/phpmyadmin/templates/display/import/javascript.twig:80\nStack trace:\n#0 /usr/share/php/Twig/ExpressionParser.php(470): Twig_ExpressionParser->getFilterNodeClass('spaceless', 80)\n#1 /usr/share/php/Twig/ExpressionParser.php(455): Twig_ExpressionParser->parseFilterExpressionRaw(Object(Twig_Node_Expression_Name))\n#2 /usr/share/php/Twig/ExpressionParser.php(313): Twig_ExpressionParser->parseFilterExpression(Object(Twig_Node_Expression_Name))\n#3 /usr/share/php/Twig/ExpressionParser.php(205): Twig_ExpressionParser->parsePostfixExpression(Object(Twig_Node_Expression_Name))\n#4 /usr/share/php/Twig/ExpressionParser.php(92): Twig_ExpressionParser->parsePrimaryExpression()\n#5 /usr/share/php/Twig/ExpressionParser.php(45): Twig_ExpressionParser->getPrimary()\n#6 /usr/share/php/Twig/Parser.php(125): Twig_ExpressionParser->parseExpression()\n#7 /usr/share/php/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array)\n#8 /usr/share/php/Twig/Parser.php(168): Twig in /usr/share/phpmyadmin/templates/display/import/javascript.twig on line 80 
```
and suggests a twig library version problem.

**Comment by ulvida** [comment]
Solved, we should have installed sid version of `php-twig` (presently 2.14.3-1) instead of buster stable version (presently 2.6.2-2). `phpmyadmin` package dependencies should be adjusted.
